// Code generated by hertz generator.

package git_sync

import (
	"context"
	"crypto/subtle"
	"log/slog"
	"net/http"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
	handler "github.com/yi-nology/git-sync-service/biz/handler/git_sync"
)

// AuthMiddleware returns a middleware that validates the X-API-Key header.
// All API endpoints must pass this check before reaching the handler.
// Uses constant-time comparison to prevent timing attacks.
// If the server API key is empty, all requests are rejected.
func AuthMiddleware() app.HandlerFunc {
	return func(ctx context.Context, c *app.RequestContext) {
		serverKey := handler.GetSyncService().GetAPIKey()
		if serverKey == "" {
			c.JSON(http.StatusUnauthorized, map[string]string{"error": "unauthorized: API key not configured"})
			c.Abort()
			return
		}
		apiKey := c.GetHeader("X-API-Key")
		if subtle.ConstantTimeCompare([]byte(apiKey), []byte(serverKey)) != 1 {
			c.JSON(http.StatusUnauthorized, map[string]string{"error": "unauthorized"})
			c.Abort()
			return
		}
		c.Next(ctx)
	}
}

// RequestLogMiddleware logs API requests with method, path, status code, and latency.
func RequestLogMiddleware() app.HandlerFunc {
	return func(ctx context.Context, c *app.RequestContext) {
		start := time.Now()
		c.Next(ctx)
		slog.Info("api request",
			"method", string(c.Method()),
			"path", string(c.Path()),
			"status", c.Response.StatusCode(),
			"latency", time.Since(start).String(),
			"client_ip", c.ClientIP(),
		)
	}
}

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	return []app.HandlerFunc{RequestLogMiddleware(), AuthMiddleware()}
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _repoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _syncMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _taskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _webhookMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listeventsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _ruleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _eventMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _retryeventMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletehistoryMw() []app.HandlerFunc {
	// TODO: Add middleware
	return nil
}

func _taskhistoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _taskpreviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _taskgetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _taskcreateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _taskdeleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _taskrunMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _taskupdateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tasklistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _rulegetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _rulecreateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _ruledeleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _ruleupdateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _rulelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _logsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listoperationlogsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _platformMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getplatformMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createplatformMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteplatformMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listplatformreposMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _setdefaultplatformMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _syncplatformreposMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _testplatformconnectionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateplatformMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listplatformsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _repogetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _repobranchesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _repocreateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _repodeleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _repotestMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _repoupdateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _repolistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reposMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _batchreposMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemstatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _platform0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteplatformwebhookMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listplatformwebhooksMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerplatformwebhookMw() []app.HandlerFunc {
	// your code...
	return nil
}
