// Code generated by hertz generator.

package git_sync

import (
	"context"
	"net/http"

	"github.com/cloudwego/hertz/pkg/app"
	handler "github.com/yi-nology/git-sync-service/biz/handler/git_sync"
)

// AuthMiddleware returns a middleware that validates the X-API-Key header.
// All API endpoints must pass this check before reaching the handler.
func AuthMiddleware() app.HandlerFunc {
	return func(ctx context.Context, c *app.RequestContext) {
		apiKey := c.GetHeader("X-API-Key")
		if string(apiKey) != handler.GetSyncService().GetAPIKey() {
			c.JSON(http.StatusUnauthorized, map[string]string{"error": "unauthorized"})
			c.Abort()
			return
		}
		c.Next(ctx)
	}
}

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	return []app.HandlerFunc{AuthMiddleware()}
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _repoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getrepoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listbranchesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createrepoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleterepoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _testconnectionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updaterepoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listreposMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _syncMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listhistoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _previewsyncMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _taskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createtaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletetaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _runtaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatetaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listtasksMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _webhookMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listeventsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _ruleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getruleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createruleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteruleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateruleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listrulesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _eventMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _retryeventMw() []app.HandlerFunc {
	// your code...
	return nil
}
