run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - gofmt
    - goimports
    - misspell
  
  disable:
    - deadcode
    - structcheck
    - varcheck

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  
  goimports:
    local-prefixes: github.com/yi-nology/git-sync-service

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default-severity: warning
  rules:
    - linters:
        - errcheck
      severity: error
