version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: standard
  enable:
    - gocritic
    - misspell

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - unnamedResult
        - builtinShadow

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
