// Code generated by hertz generator.

package main

import (
	"fmt"
	"log"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/yi-nology/git-sync-service/biz/handler/git_sync"
	"github.com/yi-nology/git-sync-service/sync"
)

var syncSvc *sync.Service

func main() {
	cfg, err := sync.LoadConfig("conf/config.yaml")
	if err != nil {
		log.Fatalf("load config failed: %v", err)
	}

	syncSvc, err = sync.NewService(cfg)
	if err != nil {
		log.Fatalf("init sync service failed: %v", err)
	}

	if err := syncSvc.Start(); err != nil {
		log.Fatalf("start sync service failed: %v", err)
	}
	defer syncSvc.Stop()

	git_sync.SetSyncServiceGetter(func() *sync.Service {
		return syncSvc
	})

	h := server.Default(server.WithHostPorts(fmt.Sprintf("%s:%d", cfg.Server.Host, cfg.Server.Port)))

	register(h)
	h.Spin()
}
