// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "github.com/yi-nology/git-sync-service/biz/handler"
	"github.com/yi-nology/git-sync-service/biz/handler/git_sync"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// Webhook 接收端点
	r.POST("/api/v1/webhook/receive/:repoKey", git_sync.ReceiveWebhook)
}
