// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "github.com/yi-nology/git-sync-service/biz/handler"
	"github.com/yi-nology/git-sync-service/biz/handler/git_sync"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	// Liveness probe (no auth, no middleware)
	r.GET("/ping", handler.Ping)

	// Readiness probe (checks database and Redis, no auth)
	r.GET("/health", git_sync.HealthCheck)

	// Webhook 接收端点（带速率限制，不走 API 鉴权）
	r.POST("/api/webhook/receive/:repoKey", git_sync.RateLimitMiddleware(), git_sync.ReceiveWebhook)

	// POST /api/v1/repos/batch -> BatchRepos
	r.POST("/api/v1/repos/batch", git_sync.BatchRepos)
}
