// Code generated by hertz generator.

package git_sync

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	repo "github.com/yi-nology/git-sync-service/biz/model/repo"
	syncmodel "github.com/yi-nology/git-sync-service/sync/model"
)

func toRepoModel(r *syncmodel.Repo) *repo.RepoInfo {
	if r == nil {
		return nil
	}
	return &repo.RepoInfo{
		ID:            int64(r.ID),
		Key:           r.Key,
		Name:          r.Name,
		Platform:      r.Platform,
		PlatformOwner: r.PlatformOwner,
		PlatformRepo:  r.PlatformRepo,
		CloneURL:      r.CloneURL,
		SSHURL:        r.SSHURL,
		DefaultBranch: r.DefaultBranch,
		Status:        r.Status,
		CreatedAt:     r.CreatedAt.Format("2006-01-02 15:04:05"),
	}
}

func ListRepos(ctx context.Context, c *app.RequestContext) {
	var err error
	var req repo.ListReposReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	list, err := GetSyncService().ListRepos()
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{"error": err.Error()})
		return
	}

	repos := make([]*repo.RepoInfo, 0, len(list))
	for _, r := range list {
		repos = append(repos, toRepoModel(r))
	}

	resp := &repo.ListReposResp{
		Repos: repos,
		Total: int64(len(repos)),
	}

	c.JSON(consts.StatusOK, resp)
}

func GetRepo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req repo.GetRepoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	r, err := GetSyncService().GetRepo(req.Key)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{"error": err.Error()})
		return
	}

	resp := &repo.GetRepoResp{
		Repo: toRepoModel(r),
	}

	c.JSON(consts.StatusOK, resp)
}

func CreateRepo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req repo.CreateRepoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	svcReq := &syncmodel.CreateRepoRequest{
		Name:        req.Name,
		RemoteURL:   req.RemoteURL,
		AccessToken: req.AccessToken,
	}

	r, err := GetSyncService().CreateRepo(svcReq)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{"error": err.Error()})
		return
	}

	resp := &repo.CreateRepoResp{
		Repo: toRepoModel(r),
	}

	c.JSON(consts.StatusOK, resp)
}

func UpdateRepo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req repo.UpdateRepoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	svcReq := &syncmodel.UpdateRepoRequest{
		Key:         req.Key,
		Name:        req.Name,
		AccessToken: req.AccessToken,
	}

	r, err := GetSyncService().UpdateRepo(svcReq)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{"error": err.Error()})
		return
	}

	resp := &repo.UpdateRepoResp{
		Repo: toRepoModel(r),
	}

	c.JSON(consts.StatusOK, resp)
}

func DeleteRepo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req repo.DeleteRepoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	err = GetSyncService().DeleteRepo(req.Key)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{"error": err.Error()})
		return
	}

	resp := &repo.DeleteRepoResp{
		Success: err == nil,
	}

	c.JSON(consts.StatusOK, resp)
}

func TestConnection(ctx context.Context, c *app.RequestContext) {
	var err error
	var req repo.TestConnectionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	result, err := GetSyncService().TestConnection(ctx, req.Key)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{"error": err.Error()})
		return
	}

	resp := &repo.TestConnectionResp{
		Success: result.Success,
		Message: result.Message,
	}

	c.JSON(consts.StatusOK, resp)
}

func ListBranches(ctx context.Context, c *app.RequestContext) {
	var err error
	var req repo.ListBranchesReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	branches, err := GetSyncService().ListBranches(ctx, req.Key)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{"error": err.Error()})
		return
	}

	resp := &repo.ListBranchesResp{
		Branches: branches,
	}

	c.JSON(consts.StatusOK, resp)
}
