// Code generated by hertz generator.

package git_sync

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	sync_task "github.com/yi-nology/git-sync-service/biz/model/sync_task"
	synccore "github.com/yi-nology/git-sync-service/internal/sync"
	syncmodel "github.com/yi-nology/git-sync-service/internal/sync/model"
)

func toTaskModel(t *syncmodel.SyncTask) *sync_task.SyncTaskInfo {
	if t == nil {
		return nil
	}
	lastRunAt := ""
	if t.LastRunAt != nil {
		lastRunAt = t.LastRunAt.Format("2006-01-02 15:04:05")
	}
	return &sync_task.SyncTaskInfo{
		ID:            int64(t.ID),
		Key:           t.Key,
		Name:          t.Name,
		SourceRepoKey: t.SourceRepoKey,
		SourceBranch:  t.SourceBranch,
		TargetRepoKey: t.TargetRepoKey,
		TargetBranch:  t.TargetBranch,
		SyncMode:      t.SyncMode,
		Cron:          t.Cron,
		WebhookToken:  t.WebhookToken,
		Enabled:       t.Enabled,
		GitTags:       t.GitTags,
		GitForce:      t.GitForce,
		GitPrune:      t.GitPrune,
		GitNoVerify:   t.GitNoVerify,
		LastRunAt:     lastRunAt,
		LastStatus:    t.LastStatus,
		CreatedAt:     t.CreatedAt.Format("2006-01-02 15:04:05"),
	}
}

func toSyncRunModel(r *syncmodel.SyncRun) *sync_task.SyncRunInfo {
	if r == nil {
		return nil
	}
	endTime := ""
	if r.EndTime != nil {
		endTime = r.EndTime.Format("2006-01-02 15:04:05")
	}
	return &sync_task.SyncRunInfo{
		ID:            int64(r.ID),
		TaskKey:       r.TaskKey,
		TriggerSource: r.TriggerSource,
		Status:        r.Status,
		StartTime:     r.StartTime.Format("2006-01-02 15:04:05"),
		EndTime:       endTime,
		CommitRange:   r.CommitRange,
		Details:       r.Details,
		ErrorMessage:  r.ErrorMessage,
		CreatedAt:     r.CreatedAt.Format("2006-01-02 15:04:05"),
	}
}

func ListTasks(ctx context.Context, c *app.RequestContext) {
	var err error
	var req sync_task.ListTasksReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	list, err := GetSyncService().ListTasks(req.RepoKey)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{"error": err.Error()})
		return
	}

	tasks := make([]*sync_task.SyncTaskInfo, 0, len(list))
	for _, t := range list {
		tasks = append(tasks, toTaskModel(t))
	}

	resp := &sync_task.ListTasksResp{
		Tasks: tasks,
		Total: int64(len(tasks)),
	}

	c.JSON(consts.StatusOK, resp)
}

func GetTask(ctx context.Context, c *app.RequestContext) {
	var err error
	var req sync_task.GetTaskReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	t, err := GetSyncService().GetTask(req.Key)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{"error": err.Error()})
		return
	}

	resp := &sync_task.GetTaskResp{
		Task: toTaskModel(t),
	}

	c.JSON(consts.StatusOK, resp)
}

func CreateTask(ctx context.Context, c *app.RequestContext) {
	var err error
	var req sync_task.CreateTaskReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	svcReq := &syncmodel.CreateTaskRequest{
		Name:          req.Name,
		SourceRepoKey: req.SourceRepoKey,
		SourceBranch:  req.SourceBranch,
		TargetRepoKey: req.TargetRepoKey,
		TargetBranch:  req.TargetBranch,
		SyncMode:      req.SyncMode,
		Cron:          req.Cron,
		GitTags:       req.GitTags,
		GitForce:      req.GitForce,
		GitPrune:      req.GitPrune,
		GitNoVerify:   req.GitNoVerify,
		PushOptions:   req.PushOptions,
	}

	t, err := GetSyncService().CreateTask(svcReq)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{"error": err.Error()})
		return
	}

	resp := &sync_task.CreateTaskResp{
		Task: toTaskModel(t),
	}

	c.JSON(consts.StatusOK, resp)
}

func UpdateTask(ctx context.Context, c *app.RequestContext) {
	var err error
	var req sync_task.UpdateTaskReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	svcReq := &syncmodel.UpdateTaskRequest{
		Key:         req.Key,
		Name:        req.Name,
		SourceBranch: req.SourceBranch,
		TargetBranch: req.TargetBranch,
		SyncMode:    req.SyncMode,
		Cron:        req.Cron,
		Enabled:     req.Enabled,
		GitTags:      req.GitTags,
		GitForce:     req.GitForce,
		GitPrune:     req.GitPrune,
		GitNoVerify:  req.GitNoVerify,
		PushOptions:  req.PushOptions,
	}

	t, err := GetSyncService().UpdateTask(svcReq)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{"error": err.Error()})
		return
	}

	resp := &sync_task.UpdateTaskResp{
		Task: toTaskModel(t),
	}

	c.JSON(consts.StatusOK, resp)
}

func DeleteTask(ctx context.Context, c *app.RequestContext) {
	var err error
	var req sync_task.DeleteTaskReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	err = GetSyncService().DeleteTask(req.Key)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{"error": err.Error()})
		return
	}

	resp := &sync_task.DeleteTaskResp{
		Success: err == nil,
	}

	c.JSON(consts.StatusOK, resp)
}

func RunTask(ctx context.Context, c *app.RequestContext) {
	var err error
	var req sync_task.RunTaskReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	err = GetSyncService().RunTask(ctx, req.Key)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{"error": err.Error()})
		return
	}

	resp := &sync_task.RunTaskResp{
		Success: err == nil,
		Message: "task started",
	}

	c.JSON(consts.StatusOK, resp)
}

func PreviewSync(ctx context.Context, c *app.RequestContext) {
	var err error
	var req sync_task.PreviewSyncReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	svcReq := &synccore.PreviewSyncRequest{
		SourceRepoKey: req.SourceRepoKey,
		SourceBranch:  req.SourceBranch,
		TargetRepoKey: req.TargetRepoKey,
		TargetBranch:  req.TargetBranch,
	}

	result, err := GetSyncService().PreviewSync(svcReq)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{"error": err.Error()})
		return
	}

	resp := &sync_task.PreviewSyncResp{
		CanSync:      result.CanSync,
		SourceExists: result.SourceExists,
		TargetExists: result.TargetExists,
		CommitCount:  int32(result.CommitCount),
		LatestCommit: result.LatestCommit,
		Message:      result.Message,
	}

	c.JSON(consts.StatusOK, resp)
}

func ListHistory(ctx context.Context, c *app.RequestContext) {
	var err error
	var req sync_task.ListHistoryReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	list, err := GetSyncService().ListHistory(req.TaskKey, int(req.Limit))
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{"error": err.Error()})
		return
	}

	runs := make([]*sync_task.SyncRunInfo, 0, len(list))
	for _, r := range list {
		runs = append(runs, toSyncRunModel(r))
	}

	resp := &sync_task.ListHistoryResp{
		Runs: runs,
	}

	c.JSON(consts.StatusOK, resp)
}
