// Code generated by hertz generator.

package git_sync

import (
	"context"
	"runtime"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
	system "github.com/yi-nology/git-sync-service/biz/model/system"
	"github.com/yi-nology/git-sync-service/internal/converter"
	"github.com/yi-nology/git-sync-service/internal/pkg/response"
	"github.com/yi-nology/git-sync-service/internal/version"
)

// SystemStatus 返回系统状态信息（管理面板用）。
func SystemStatus(ctx context.Context, c *app.RequestContext) {
	svc := GetSyncService()

	// CountRepos 与 CountTasksByStatus 互不依赖,并行执行。
	type repoCountResult struct {
		count int64
		err   error
	}
	type taskCountResult struct {
		counts map[string]int64
		err    error
	}
	repoCh := make(chan repoCountResult, 1)
	taskCh := make(chan taskCountResult, 1)
	go func() {
		c, e := svc.CountRepos()
		repoCh <- repoCountResult{c, e}
	}()
	go func() {
		c, e := svc.CountTasksByStatus()
		taskCh <- taskCountResult{c, e}
	}()

	rr := <-repoCh
	if rr.err != nil {
		response.InternalError(c, "get repo count failed")
		return
	}
	tr := <-taskCh
	if tr.err != nil {
		response.InternalError(c, "get task count failed")
		return
	}
	repoCount := rr.count
	taskCounts := tr.counts
	taskTotal := taskCounts["total"]
	runningCount := taskCounts["running"]
	failedCount := taskCounts["failed"]

	response.Success(c, &system.SystemStatusData{
		Status:      "running",
		Version:     version.Version,
		Uptime:      int64(time.Since(startTime).Seconds()),
		RepoCount:   converter.SafeInt64ToInt32(repoCount),
		TaskCount:   converter.SafeInt64ToInt32(taskTotal),
		RunningTask: converter.SafeInt64ToInt32(runningCount),
		FailedTask:  converter.SafeInt64ToInt32(failedCount),
		GoVersion:   runtime.Version(),
		Platform:    runtime.GOOS + "/" + runtime.GOARCH,
	})
}
