// Code generated by hertz generator.

package git_sync

import (
	"context"
	"runtime"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
	system "github.com/yi-nology/git-sync-service/biz/model/system"
	"github.com/yi-nology/git-sync-service/internal/converter"
	"github.com/yi-nology/git-sync-service/internal/pkg/response"
)

// SystemStatus 返回系统状态信息（管理面板用）。
func SystemStatus(ctx context.Context, c *app.RequestContext) {
	svc := GetSyncService()

	// 计数走 COUNT 聚合,不再全表加载进内存
	repoCount, err := svc.CountRepos()
	if err != nil {
		response.InternalError(c, "get repo count failed")
		return
	}
	taskCounts, err := svc.CountTasksByStatus()
	if err != nil {
		response.InternalError(c, "get task count failed")
		return
	}
	taskTotal := taskCounts["total"]
	runningCount := taskCounts["running"]
	failedCount := taskCounts["failed"]

	response.Success(c, &system.SystemStatusData{
		Status:      "running",
		Version:     "v1.6.3",
		Uptime:      int64(time.Since(startTime).Seconds()),
		RepoCount:   converter.SafeInt64ToInt32(repoCount),
		TaskCount:   converter.SafeInt64ToInt32(taskTotal),
		RunningTask: converter.SafeInt64ToInt32(runningCount),
		FailedTask:  converter.SafeInt64ToInt32(failedCount),
		GoVersion:   runtime.Version(),
		Platform:    runtime.GOOS + "/" + runtime.GOARCH,
	})
}
