// Code generated by hertz generator.

package git_sync

import (
	"context"
	"runtime"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
	system "github.com/yi-nology/git-sync-service/biz/model/system"
	"github.com/yi-nology/git-sync-service/internal/pkg/response"
)

// SystemStatus 返回系统状态信息（管理面板用）。
func SystemStatus(ctx context.Context, c *app.RequestContext) {
	svc := GetSyncService()

	// 取计数（用大 limit 取全部）
	repos, _, _ := svc.ListRepos(ctx, 0, 10000)
	tasks, _, _ := svc.ListTasks(ctx, "", 0, 10000)

	runningCount := 0
	failedCount := 0
	for _, t := range tasks {
		if t.LastStatus == "running" {
			runningCount++
		}
		if t.LastStatus == "failed" {
			failedCount++
		}
	}

	response.Success(c, &system.SystemStatusData{
		Status:      "running",
		Version:     "v1.5.0",
		Uptime:      int64(time.Since(startTime).Seconds()),
		RepoCount:   int32(len(repos)),
		TaskCount:   int32(len(tasks)),
		RunningTask: int32(runningCount),
		FailedTask:  int32(failedCount),
		GoVersion:   runtime.Version(),
		Platform:    runtime.GOOS + "/" + runtime.GOARCH,
	})
}
