// Code generated by hertz generator.

package git_sync

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	webhook "github.com/yi-nology/git-sync-service/biz/model/webhook"
	syncmodel "github.com/yi-nology/git-sync-service/internal/sync/model"
)

func toRuleModel(r *syncmodel.WebhookRule) *webhook.WebhookRuleInfo {
	if r == nil {
		return nil
	}
	return &webhook.WebhookRuleInfo{
		ID:             int64(r.ID),
		Name:           r.Name,
		RepoKey:        r.RepoKey,
		EventType:      r.EventType,
		BranchPattern:  r.BranchPattern,
		Action:         r.Action,
		SyncTaskKeys:   r.SyncTaskKeys,
		MinInterval:    int32(r.MinInterval),
		Enabled:        r.Enabled,
		Description:    r.Description,
		CreatedAt:      r.CreatedAt.Format("2006-01-02 15:04:05"),
	}
}

func toEventModel(e *syncmodel.WebhookEvent) *webhook.WebhookEventInfo {
	if e == nil {
		return nil
	}
	processedAt := ""
	if e.ProcessedAt != nil {
		processedAt = e.ProcessedAt.Format("2006-01-02 15:04:05")
	}
	return &webhook.WebhookEventInfo{
		ID:            int64(e.ID),
		EventID:       e.EventID,
		RepoKey:       e.RepoKey,
		EventType:     e.EventType,
		Source:        e.Source,
		ActorName:     e.ActorName,
		Branch:        e.Branch,
		CommitSha:     e.CommitSHA,
		Status:        e.Status,
		ErrorMessage:  e.ErrorMessage,
		ProcessedAt:   processedAt,
		CreatedAt:     e.CreatedAt.Format("2006-01-02 15:04:05"),
	}
}

func ListRules(ctx context.Context, c *app.RequestContext) {
	var err error
	var req webhook.ListRulesReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	list, err := GetSyncService().ListRules(req.RepoKey)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{"error": err.Error()})
		return
	}

	rules := make([]*webhook.WebhookRuleInfo, 0, len(list))
	for _, r := range list {
		rules = append(rules, toRuleModel(r))
	}

	resp := &webhook.ListRulesResp{
		Rules: rules,
	}

	c.JSON(consts.StatusOK, resp)
}

func GetRule(ctx context.Context, c *app.RequestContext) {
	var err error
	var req webhook.GetRuleReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	r, err := GetSyncService().GetRule(uint(req.ID))
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{"error": err.Error()})
		return
	}

	resp := &webhook.GetRuleResp{
		Rule: toRuleModel(r),
	}

	c.JSON(consts.StatusOK, resp)
}

func CreateRule(ctx context.Context, c *app.RequestContext) {
	var err error
	var req webhook.CreateRuleReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	svcReq := &syncmodel.CreateRuleRequest{
		Name:          req.Name,
		RepoKey:       req.RepoKey,
		EventType:     req.EventType,
		BranchPattern: req.BranchPattern,
		Action:        req.Action,
		SyncTaskKeys:  req.SyncTaskKeys,
		MinInterval:   int(req.MinInterval),
		Enabled:       req.Enabled,
		Description:   req.Description,
	}

	r, err := GetSyncService().CreateRule(svcReq)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{"error": err.Error()})
		return
	}

	resp := &webhook.CreateRuleResp{
		Rule: toRuleModel(r),
	}

	c.JSON(consts.StatusOK, resp)
}

func UpdateRule(ctx context.Context, c *app.RequestContext) {
	var err error
	var req webhook.UpdateRuleReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	svcReq := &syncmodel.UpdateRuleRequest{
		ID:            uint(req.ID),
		Name:          req.Name,
		EventType:     req.EventType,
		BranchPattern: req.BranchPattern,
		Action:        req.Action,
		SyncTaskKeys:  req.SyncTaskKeys,
		MinInterval:   int(req.MinInterval),
		Enabled:       req.Enabled,
		Description:   req.Description,
	}

	r, err := GetSyncService().UpdateRule(svcReq)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{"error": err.Error()})
		return
	}

	resp := &webhook.UpdateRuleResp{
		Rule: toRuleModel(r),
	}

	c.JSON(consts.StatusOK, resp)
}

func DeleteRule(ctx context.Context, c *app.RequestContext) {
	var err error
	var req webhook.DeleteRuleReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	err = GetSyncService().DeleteRule(uint(req.ID))
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{"error": err.Error()})
		return
	}

	resp := &webhook.DeleteRuleResp{
		Success: err == nil,
	}

	c.JSON(consts.StatusOK, resp)
}

func ListEvents(ctx context.Context, c *app.RequestContext) {
	var err error
	var req webhook.ListEventsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	list, err := GetSyncService().ListEvents(req.RepoKey, int(req.Limit))
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{"error": err.Error()})
		return
	}

	events := make([]*webhook.WebhookEventInfo, 0, len(list))
	for _, e := range list {
		events = append(events, toEventModel(e))
	}

	resp := &webhook.ListEventsResp{
		Events: events,
	}

	c.JSON(consts.StatusOK, resp)
}

func RetryEvent(ctx context.Context, c *app.RequestContext) {
	var err error
	var req webhook.RetryEventReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	err = GetSyncService().RetryEvent(ctx, uint(req.ID))
	if err != nil {
		c.JSON(consts.StatusInternalServerError, map[string]interface{}{"error": err.Error()})
		return
	}

	resp := &webhook.RetryEventResp{
		Success: err == nil,
		Message: "event retried",
	}

	c.JSON(consts.StatusOK, resp)
}
